const path=require('node:path');const root=path.resolve(__dirname,'..');const fixtures=process.env.PHOTO_FIXTURE_DIR;if(!fixtures)throw new Error('Set PHOTO_FIXTURE_DIR to the folder containing IMG_0747.jpeg through IMG_0751.jpeg');const assert=require('node:assert/strict');const {chromium}=require(require.resolve('playwright',{paths:[process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES||root,root]}));const server=require('child_process').spawn('python',['-m','http.server','8765','--bind','127.0.0.1'],{cwd:root,stdio:'ignore'});
(async()=>{await new Promise(r=>setTimeout(r,300));const b=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_EXECUTABLE||undefined,args:['--no-sandbox']});try{const page=await b.newPage({viewport:{width:390,height:844}});const errors=[];page.on('pageerror',e=>errors.push(e.message));if(process.env.DEBUG_OCR)page.on('console',e=>console.log(e.text()));await page.goto('http://127.0.0.1:8765/');await page.route('**/upload/*.jpeg',route=>route.fulfill({path:path.join(fixtures,path.basename(new URL(route.request().url()).pathname)),contentType:'image/jpeg'}));
if(process.env.DEBUG_OCR)await page.evaluate(()=>window.__PAWAADO_DEBUG_OCR__=true);const academy=await page.evaluate(async()=>{const out=[];for(const n of [748,749,750,751]){const im=new Image();im.src='/upload/IMG_0'+n+'.jpeg';await im.decode();out.push(await __PAWAADO_PHOTO_TEST__.academyOf(im));}return out;});assert.deepEqual(academy,['ブートレインアカデミー','パワフルアカデミー','タテレスキュアアカデミー','カジナイトアカデミー']);console.log('PASS all four academy references');
await page.locator('#photoFiles').setInputFiles([path.join(fixtures,'IMG_0747.jpeg'),path.join(fixtures,'IMG_0748.jpeg')]);await page.locator('#readPhotos').click();await page.locator('#photoReview').waitFor({state:'visible',timeout:90000});const vals=await page.locator('#photoReview input[type=number]').evaluateAll(es=>es.map(e=>Number(e.value)));assert.deepEqual(vals,[690,238,351,273,451,12,8,14,9,9,8]);assert.equal(await page.locator('#photoOwnedSummary').textContent(),'魔法攻撃○');
await page.locator('#photoConfirmed').check();await page.locator('#applyPhotos').click();assert.match(await page.locator('#photoStatus').textContent(),/反映しました/);assert.equal(await page.locator('#academy').inputValue(),'ブートレインアカデミー');assert.equal(await page.locator('#job').inputValue(),'剣士');assert.equal(await page.locator('#basic_生命力').inputValue(),'12');assert.equal(await page.locator('[data-exp-name="筋力"]').inputValue(),'690');assert.ok(await page.locator('#calcBtn').isEnabled());
const idx=await page.evaluate(()=>PAWAADO_DATA.special.findIndex(s=>s[1]==='魔法攻撃○'));assert.ok(await page.locator(`.skill-row[data-index="${idx}"]`).evaluate(e=>e.classList.contains('owned')));console.log('PASS screenshot OCR and input import');
await page.locator('.super-name').selectOption('鉄人');await page.locator('.super-level').selectOption('2');const rows=await page.evaluate(()=>__PAWAADO_GET_EXTRA_RESISTANCES__());assert.deepEqual(rows,[{name:'鉄人',type:'物理攻撃耐性',value:7},{name:'鉄人',type:'魔法攻撃耐性',value:7}]);const injury=await page.evaluate(()=>PAWAADO_DATA.special.findIndex(s=>s[1]==='ケガしにくさ◎'));assert.ok(await page.locator(`.skill-row[data-index="${injury}"]`).evaluate(e=>e.classList.contains('owned')));await page.locator('.super-name').selectOption('火事場の馬鹿力');assert.deepEqual(await page.evaluate(()=>__PAWAADO_GET_EXTRA_RESISTANCES__()),[{name:'火事場の馬鹿力',type:'被ダメージ耐性',value:-4}]);console.log('PASS super selection, included lower ability, negative resistance');
const parsed=await page.evaluate(()=>__PAWAADO_PHOTO_TEST__.findSpecials('鉄人Lv2\n超免疫Lv1\n魔法攻撃◎\n慈愛の祈りLv2'));assert.deepEqual(parsed.supers,[{name:'鉄人',level:2},{name:'超免疫',level:1},{name:'慈愛の祈り',level:2}]);assert.deepEqual(new Set(parsed.specials),new Set(['魔法攻撃◎','魔法攻撃○','ケガしにくさ◎','ケガしにくさ○','免疫強化']));
const prerequisiteChecks=await page.evaluate(()=>Object.entries(PAWAADO_DATA.superPrerequisites).map(([name,lowers])=>{
  const parsed=__PAWAADO_PHOTO_TEST__.findSpecials(name);
  const expected=lowers.flatMap(n=>[n,PAWAADO_DATA.special.find(s=>s[1]===n)?.[2]]).filter(n=>PAWAADO_DATA.special.some(s=>s[1]===n));
  return {name,expected,owned:parsed.specials,detected:parsed.supers.map(s=>s.name)};
}));
for(const c of prerequisiteChecks){assert.deepEqual(c.detected,[c.name]);assert.deepEqual(new Set(c.owned),new Set(c.expected));}
assert.deepEqual(await page.evaluate(()=>__PAWAADO_PHOTO_TEST__.findSpecials('烈火').supers),[]);
const imported=await page.evaluate(()=>{
  __PAWAADO_IMPORT_PHOTO__({academy:'ブートレインアカデミー',job:'剣士',exp:{筋力:690,敏捷:238,技術:351,知力:273,精神:451},basic:{生命力:12,パワー:8,魔力:14,器用さ:9,耐久力:9,精神力:8},specials:['通常攻撃◎'],supers:Object.keys(PAWAADO_DATA.superPrerequisites).filter(n=>!PAWAADO_DATA.superResistances[n]).map(name=>({name,level:null}))});
  return [...document.querySelectorAll('.skill-row.owned')].map(el=>PAWAADO_DATA.special[Number(el.dataset.index)][1]);
});
const expectedOwned=prerequisiteChecks.filter(c=>!['鉄人','超免疫'].includes(c.name)).flatMap(c=>c.expected);
assert.deepEqual(new Set(imported),new Set(expectedOwned));assert.equal(imported.length,new Set(imported).size);
console.log('PASS 11 upper-ability mappings, prerequisite chains, deduplication, and one-character name boundary');
assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.evaluate(()=>window.scrollTo(0,0));
await page.locator('#topResetBtn').click();assert.equal(await page.locator('#photoFiles').inputValue(),'');assert.equal(await page.locator('#academy').inputValue(),'');assert.equal(await page.locator('.super-name').inputValue(),'');assert.equal(await page.locator('#photoReview').isVisible(),false);assert.deepEqual(errors,[]);console.log('PASS parser, mobile width, reset; no page errors');}finally{await b.close();server.kill();}})().catch(e=>{console.error(e);server.kill();process.exit(1)});
